---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- import_tasks: rules.yml

- include_tasks: persist-debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: persist-solaris.yml
  when: ansible_os_family == 'Solaris'
