---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"
  tags: [always]

- include: rules.yml

- include: persist-debian.yml
  when: ansible_os_family == 'Debian'

- include: persist-solaris.yml
  when: ansible_os_family == 'Solaris'
