- name: ipfilter | Create unit file
  template: src=ipfilter.service.j2 dest=/etc/systemd/system/ipfilter.service
  when: ansible_service_mgr == 'systemd'

- name: ipfilter | Create old init.d file
  template: src=debian_service.j2 dest=/etc/init.d/ipfilter mode=0755
  when: ansible_service_mgr == 'service'
